feat: Jenkins fetch coverage
platform-platform/monorepo pull request #1055
Opened 2021-02-03 09:47 UTC by solid-tetianamovlian

Fixes #1033 

## Checklist

- [ ] Documented
- [ ] Unit tested

2021-02-04 13:04 UTC, solid-vladlaba requested changes
Well done, @solid-maxim @solid-tetianamovlian! I've added a couple of suggestions below - please let me know what you think!

2021-02-04 13:04 UTC, solid-vladlaba commented on metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
> +      ".fetchCoverage() returns null if an artifact bytes are null",
```suggestion
      ".fetchCoverage() returns null if an artifact content is null",
```

2021-02-04 13:04 UTC, solid-vladlaba commented on metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
> +
```suggestion
```

2021-02-04 13:04 UTC, solid-vladlaba commented on metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
> +        expect(actualAPIUrl, equals(expectedAPIUrl));
```suggestion
        const build = BuildData(buildNumber: 1);
        const jenkinsBuild = JenkinsBuild(
          number: 2,
          url: defaultBuildUrl,
          building: false,
          artifacts: [defaultArtifact],
        );
        final expectedAPIUrl =
            '${jenkinsBuild.url}${JenkinsClient.jsonApiPath}';
       
        responses.addBuilds([jenkinsBuild]);
        whenFetchBuilds().thenAnswer(responses.fetchBuilds);

        final result = await adapter.fetchBuildsAfter(jobName, build);
        final actualAPIUrl = result.first.apiUrl;

        expect(actualAPIUrl, equals(expectedAPIUrl));
```

2021-02-04 13:04 UTC, solid-vladlaba commented on metrics/ci_integrations/test/source/jenkins/adapter/jenkins_source_client_adapter_test.dart
> +        expect(actualAPIUrl, isNull);
```suggestion
        const build = BuildData(buildNumber: 1);
        const jenkinsBuild = JenkinsBuild(
          number: 2,
          url: null,
          building: false,
          artifacts: [defaultArtifact],
        );

        responses.addBuilds([jenkinsBuild]);
        whenFetchBuilds().thenAnswer(responses.fetchBuilds);

        final result = await adapter.fetchBuildsAfter(jobName, build);
        final actualAPIUrl = result.first.apiUrl;

        expect(actualAPIUrl, isNull);
```

2021-02-08 17:01 UTC, illia-romanenko approved these changes
I did a quick scan - all looks good to me - thanks @solid-tetianamovlian @solid-maxim  @solid-vladlaba !

2021-02-08 17:45 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-maxim @solid-tetianamovlian!:rocket: 
I've performed a couple of improvements and introduced several classes to make Jenkins integration more granular and clear. Please review them and let me know what you think!

2021-02-08 17:45 UTC, merged