feat: Add license banner
platform-platform/monorepo pull request #1062
Opened 2021-02-04 13:06 UTC by solid-tetianamovlian

Fixes #1039

2021-02-04 14:24 UTC, solid-vladlaba requested changes
Well done, @solid-tetianamovlian @solid-maxim! I've added a couple of suggestions below - please let me know what you think!

2021-02-05 10:05 UTC, solid-tetianamovlian commented on .licenserc.json
> +  "**/*.js": [
As we’ve tested, multiple file extensions currently are not working.

2021-02-05 14:56 UTC, solid-maxim commented on .licenserc.json
> +  "**/*.js": [
In the updated version of the License checker, this issue was resolved. So we've fixed this according to the suggestion.

2021-02-08 08:26 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-tetianamovlian @solid-maxim!:rocket:

2021-02-08 08:27 UTC, merged