feat: Implement a bar chart to match latest design
platform-platform/monorepo pull request #1113
Opened 2021-02-17 09:12 UTC by solid-tetianamovlian

Fixes #1102 

## Checklist

- [ ] Documented
- [ ] Component tested

2021-02-17 11:58 UTC, solid-vladlaba requested changes
Well done, @solid-maxim @solid-tetianamovlian! I've added a couple of suggestions below - please let me know what you think!

2021-02-17 11:58 UTC, solid-vladlaba commented on metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
> +  static const double graphIndicatorOuterDiameter = 7.0;
It seems like the indicator is `10.0` in diameter now: 
![image](https://user-images.githubusercontent.com/70939496/108198405-3fea1980-7124-11eb-90b8-b9e273c416fa.png)

2021-02-17 11:58 UTC, solid-vladlaba commented on metrics/web/lib/common/presentation/metrics_theme/config/dimensions_config.dart
> +  static const double graphIndicatorInnerDiameter = 2.8;
It seems like the inner diameter is equal to `4.0`.
![image](https://user-images.githubusercontent.com/70939496/108199118-357c4f80-7125-11eb-8231-e6da1e98e099.png)

2021-02-17 11:58 UTC, solid-vladlaba commented on metrics/web/lib/dashboard/presentation/widgets/metrics_table_row.dart
> +              width: 334.0,
Should we maybe rethink this moment as there is a `28.0` padding from the box with a name to the build results graph? Also, it appears that the whole tile has symmetric horizontal `32.0` padding, but now it is `const EdgeInsets.only(left: 32.0, right: 26.0)`.
![image](https://user-images.githubusercontent.com/70939496/108200930-ceac6580-7127-11eb-8158-e9922b7220c3.png)
![image](https://user-images.githubusercontent.com/70939496/108201040-f4396f00-7127-11eb-81d9-64e270920145.png)

2021-02-18 16:16 UTC, solid-tetianamovlian commented
I have read the CLA Document and I hereby sign the CLA

2021-02-19 13:43 UTC, solid-vladlaba commented
I have read the CLA Document and I hereby sign the CLA

2021-02-19 13:46 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-maxim @solid-tetianamovlian!:rocket: I've added minor fixes related to calculations and widget tree - please let me know what you think! 
Changes look good overall!

2021-02-19 14:02 UTC, merged