feat: Implement BuildkiteSourceValidator, BuildkiteSourceValidatorFactory
platform-platform/monorepo pull request #1114
Opened 2021-02-17 14:08 UTC by solid-daniyilyevtyushkin

Fixes #1020

## Checklist

- [x] Documented
- [x] Unit tested

2021-02-17 17:30 UTC, solid-vovabeloded requested changes
Great job, @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva! I've left a few suggestions below - please take a look.

2021-02-17 17:30 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
> +      BuildkiteToken withAccessToken,
```suggestion
      BuildkiteToken accessToken,
```

2021-02-17 17:30 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
> +      ".validate() returns a validation result with the access token field validation result, having the additional context equal to the message returned by the validation delegate if the access toke
```suggestion
      ".validate() returns a validation result with the access token field validation result, having the interaction result message as an additional context",
```

2021-02-17 17:30 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
> +      ".validate() returns a validation result with the unknown organization slug field validation result if the access token is invalid",
Would it be better to test that the validate method calls the `setEmptyResults` method after auth token validation failed?

2021-02-17 17:30 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
> +      ".validate() returns a validation result with the successful access token field validation result if the access token is valid",
Would it be better to test that the validate method sets the right auth field validation result after auth validation?

2021-02-18 13:22 UTC, solid-vovabeloded requested changes
Almost there, @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva! I've added a few more suggestions here - please take a look. Overall, the tests look great, thanks!

2021-02-18 13:22 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/source/buildkite/config/validator/buildkite_source_validator_test.dart
> +    tearDown(() {
Would it be great to move the `tearDown` method to be right above the test cases?

2021-02-19 09:10 UTC, solid-daniyilyevtyushkin commented
I have read the CLA Document and I hereby sign the CLA

2021-02-19 13:09 UTC, solid-vovabeloded commented
I have read the CLA Document and I hereby sign the CLA

2021-02-19 13:17 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva!

2021-02-19 13:17 UTC, merged