feat: Add an empty user-agent header for the API calls
platform-platform/monorepo pull request #1118
Opened 2021-02-19 08:37 UTC by solid-maxim

Fixes #1105 

## Checklist

- [ ] Documented
- [ ] Unit tested

2021-02-19 14:27 UTC, solid-vladlaba requested changes
Well done, @solid-maxim @solid-tetianamovlian! I've added one suggestion below - please let me know what you think. Also, please apply this suggestion to all of the clients in this PR.

2021-02-19 14:27 UTC, solid-vladlaba commented on metrics/ci_integrations/lib/client/buildkite/buildkite_client.dart
> +      HttpHeaders.userAgentHeader: null,
What if we introduce the optional `headers` parameter for the client? There also be a private parameter `_headers` with values to apply to all API calls as follows:
```suggestion
      if (_headers != null) ..._headers,
```
In the constructor: `: _headers = headers;`
Thus, we can separate our requirements related to an empty `user-agent` from the low-level client implementation.

2021-02-19 17:11 UTC, solid-vladlaba submitted a review, later dismissed
Looks better, @solid-maxim @solid-tetianamovlian! A few more small suggestions below - please let me know what you think!

2021-02-19 17:11 UTC, solid-vladlaba commented on metrics/ci_integrations/lib/source/buildkite/client_factory/buildkite_source_client_factory.dart
> +    };
Would it be better to introduce some class with constants to place there this map with the default headers for the CI Integrations tool? So, here and in other places we can just `SomeConstants.defaultHeaders`. Also, can this map be `const`?
```suggestion
    const headers = {
      HttpHeaders.userAgentHeader: null,
    };
```

2021-02-19 17:11 UTC, solid-vladlaba commented on metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
> +        expect(headers, containsPair(expectedHeader.key, expectedHeader.value));
```suggestion
        const expectedKey = 'test-header';
        const expectedValue = 'test-value';
        const additionalHeaders = {
          expectedKey: expectedValue,
        };

        final client = BuildkiteClient(
          buildkiteApiUrl: buildkiteMockServer.url,
          organizationSlug: organizationSlug,
          authorization: authorization,
          headers: additionalHeaders,
        );
        final headers = client.headers;
        
        expect(headers, containsPair(expectedKey, expectedValue));
```
Please apply to similar test cases.

2021-02-22 11:51 UTC, illia-romanenko approved these changes
LGTM - thanks @solid-maxim @solid-tetianamovlian !

2021-02-22 11:52 UTC, merged