feat: Implement Jenkins models
platform-platform/monorepo pull request #1127
Opened 2021-02-24 15:09 UTC by solid-yevheniiashchypeleva

Fixes #1076

## Checklist

- [x] Documented
- [x] Unit tested

2021-02-24 15:11 UTC, solid-yevheniiashchypeleva commented
I have read the CLA Document and I hereby sign the CLA

2021-02-25 11:59 UTC, solid-vovabeloded requested changes
Nicely done, @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva! I've added a few suggestions here - please take a look. Overall, the code looks great - thanks!

2021-02-25 11:59 UTC, solid-vovabeloded commented on metrics/ci_integrations/lib/client/jenkins/model/jenkins_instance_info.dart
> +  static List<JenkinsInstanceInfo> listFromJson(List<dynamic> list) {
Do we actually need this method here?

2021-02-25 11:59 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/client/jenkins/model/jenkins_instance_info_test.dart
> +  });
Should we test the `toString` method override? The same suggestions for the `JenkinsUser` class.

2021-02-25 16:40 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva!

2021-02-25 16:40 UTC, merged