docs: Web in-progress builds
platform-platform/monorepo pull request #1183
Opened 2021-03-15 11:58 UTC by solid-vladlaba

Fixes #1176 

## Checklist

- [x] Documented

2021-03-15 17:29 UTC, solid-vovabeloded requested changes
Excellent job, @solid-vladlaba! I've added a couple of suggestions here - please review them. Overall, the document looks great and easy-to-read, and the diagrams clearly describe the required changes.

2021-03-15 17:29 UTC, solid-vovabeloded commented on metrics/web/docs/features/in_progress_builds/diagrams/domain_layer_class_diagram.puml
> +    }
```suggestion
        ReceiveProjectMetricsUpdates --> DashboardProjectMetrics: creates
        ReceiveProjectMetricsUpdates --> MetricsRepository : uses
    }
```
It seems like this relation is missing.

2021-03-16 16:01 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-vladlaba! The document looks awesome!

2021-03-17 09:44 UTC, solid-vladlaba commented
@Mergifyio refresh

2021-03-17 09:45 UTC, merged