docs: Update Config Validator with new validation result
platform-platform/monorepo pull request #1185
Opened 2021-03-16 12:14 UTC by solid-yevheniiashchypeleva

Fixes #1175

## Checklist

- [x] Documented

2021-03-16 16:29 UTC, solid-vovabeloded requested changes
Great job, @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva! I've added a couple of minor suggestions - please take a look. Overall, the document updates look good, thanks!

2021-03-16 16:29 UTC, solid-vovabeloded commented on metrics/ci_integrations/docs/diagrams/config_validator_destination_class_diagram.puml
> +                class FieldValidationResult<T> {
It seems like we've missed the relation between this class and `CoolIntegrationDestinationValidationDelegate` class.

2021-03-16 16:29 UTC, solid-vovabeloded commented on metrics/ci_integrations/docs/diagrams/config_validator_sequence_diagram.puml
> +    CoolIntegrationDestinationValidationDelegate --> CoolIntegrationDestinationValidator : authFieldValidationResult
```suggestion
    CoolIntegrationDestinationValidationDelegate --> CoolIntegrationDestinationValidator : FieldValidationResult.success
```
Would it be a bit more clear? If so, please, apply this suggestion to all similar situations.

2021-03-17 09:41 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva!

2021-03-17 10:09 UTC, solid-daniyilyevtyushkin commented
@Mergifyio refresh

2021-03-17 10:10 UTC, merged