feat: Implement `.fetchOneBuild()` in the GithubActionsSourceClientAdapter
platform-platform/monorepo pull request #1288
Opened 2021-04-13 15:47 UTC by solid-vovabeloded

Fixes #1287 

## Checklist

- [x] Documented
- [x] Unit tested

2021-04-15 17:20 UTC, solid-vladlaba requested changes
Good job, @solid-vovabeloded! I've added a couple of suggestions below - please let me know what you think! Overall, the changes look great and very well-tested - thank you!

2021-04-15 17:20 UTC, solid-vladlaba commented on metrics/ci_integrations/test/source/github_actions/adapter/github_actions_source_client_adapter_test.dart
> +      ".fetchOneBuild() does not fetch the next workflow run jobs page if the previous one contains the job with the given name",
The same suggestion here, as for workflow runs page in the above.

2021-04-16 08:47 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-vovabeloded!:rocket:

2021-04-16 09:06 UTC, illia-romanenko commented
I have read the CLA Document and I hereby sign the CLA

2021-04-16 09:09 UTC, merged