feat: Implement `InProgressBuildsSyncStage`
platform-platform/monorepo pull request #1316
Opened 2021-04-21 11:37 UTC by solid-daniyilyevtyushkin

Fixes #1293

## Checklist

- [x] Documented
- [x] Unit tested

2021-04-21 16:27 UTC, solid-vladlaba requested changes
Well done, @solid-daniyilyevtyushkin @solid-yevheniiashchypeleva! I've added a couple of suggestions below - please let me know what you think!

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +      ".call() does not update a build if it is null after refresh and does not exceed a timeout",
```suggestion
      ".call() does not update a build if the corresponding build is null and the current one is not timed out",
```

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +        ));
Same as for the previous test case.

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +      ".call() does not update a build if it does not exceed a timeout and refreshing this build fails",
```suggestion
      ".call() does not update a build if fetching the corresponding build fails and the build is not timed out",
```

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +        ));
Same as for the previous test case.

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +      ".call() times out a build if it is in-progress after refresh and exceeds a timeout",
```suggestion
      ".call() updates a build as timed out if the corresponding build is in progress and the build exceeds a timeout duration",
```

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +      ".call() times out a build if it is null after refresh and exceeds a timeout",
```suggestion
      ".call() updates a build as timed out if the corresponding build is null and the build exceeds a timeout duration",
```

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +      ".call() times out a build if it exceeds a timeout and refreshing this build fails",
```suggestion
      ".call() updates a build as timed out if it exceeds a timeout duration and fetching the corresponding build fails",
```

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +      ".call() updates a build if it is finished after refresh",
```suggestion
      ".call() updates a build if the corresponding build is finished",
```

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +      ".call() does not continue the sync if fetching coverage for a build fails with an error",
```suggestion
      ".call() does not continue syncing if fetching coverage for a build fails with an error",
```

2021-04-21 16:27 UTC, solid-vladlaba commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +        final inProgressBuilds = [inProgressBuild, anotherInProgressBuild];
There is the `inProgressBuilds` variable for the group - should we use it somehow in the last test cases?

2021-04-23 09:04 UTC, solid-vovabeloded requested changes
Great job, @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva! I've added a few suggestions here - please review them.

2021-04-23 09:04 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/integration/ci/sync_stage/builds/in_progress_builds_sync_stage_test.dart
> +        ).thenAnswer((_) => Future.value(null));
```suggestion
        ).thenAnswer((_) => Future.value());
```
Please, apply this suggestion to all similar situations.

2021-04-23 11:03 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva!

2021-04-23 11:18 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-daniyilyevtyushkin @solid-yevheniiashchypeleva !:rocket:

2021-04-23 11:19 UTC, merged