docs: Update top-level readme
platform-platform/monorepo pull request #1374
Opened 2021-05-13 13:05 UTC by solid-daniyilyevtyushkin

Fixes #1362

## Checklist

- [x] Documented

2021-05-14 13:43 UTC, solid-vovabeloded requested changes
Well done, @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva! I've added a couple of suggestions here - please take a look.

2021-05-14 13:43 UTC, solid-vovabeloded commented on readme.md
> +
```suggestion
    tearDownAll(() async {
      await mockServer.close();
    });
```
Does it make sense?

2021-05-14 13:43 UTC, solid-vovabeloded commented on readme.md
> +[Guardian](guardian) is a tool for detecting and publishing flaky tests by analyzing JUnit XML files. The tool accepts the unit test reports and compares the actual and previous test results stored i
```suggestion
[Guardian](guardian) is a tool for detecting and notifying about flaky tests by analyzing JUnit XML files. This tool accepts the unit test reports and compares the actual and previous test results stored in a database. If the test is considered flaky, Guardian notifies the team using Slack and creates an issue in Jira.
```
What do you think? Also, would it be great to have a `Features` subsection in this section?

2021-05-14 13:43 UTC, solid-vovabeloded commented on readme.md
> +[YAML Map](yaml_map) is a wrapper around Dart's [`yaml`](https://pub.dev/packages/yaml) that simplifies working with YAML documents.
```suggestion
[YAML Map](yaml_map) is a wrapper around Dart's [`yaml`](https://pub.dev/packages/yaml) package that simplifies working with YAML documents.
```
Does it make sense?

2021-05-14 13:43 UTC, solid-vovabeloded commented on readme.md
> +3. [Collaboration :raised_hands:](docs/10_collaboration.md)
Would it be useful to add links to the `Effective Dart` and `process` document here?

2021-05-14 13:43 UTC, solid-vovabeloded commented on readme.md
> +Consider this useful links that may help you to get started:
```suggestion
Consider these useful links that may help you to get started:
```
?

2021-05-14 13:43 UTC, solid-vovabeloded commented on readme.md
> +# :scroll: License
Would it be useful to add a link for the dependencies licenses document here? What do you think?

2021-05-17 10:41 UTC, solid-vovabeloded requested changes
Great job, @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva! I've added a few more suggestions here - please take a look.

2021-05-17 10:41 UTC, solid-vovabeloded commented on readme.md
> +This repository holds the source code for the following projects:
```suggestion
This repository holds the source code of the following projects:
```
?

2021-05-17 10:41 UTC, solid-vovabeloded commented on readme.md
> +- Flexible request URL matching (using `ExactPathMatcher`, `RegExpPathMatcher`).
```suggestion
- Flexible request URL matching (using `ExactPathMatcher` or `RegExpPathMatcher`).
```
Does it make sense?

2021-05-17 10:41 UTC, solid-vovabeloded commented on readme.md
> +- [CI Integrations](metrics/ci_integrations) - a CLI application that integrates with popular CI tools to collect software project metrics, such as Jenkins, GitHub Actions, and Buildkite.
```suggestion
- [CI Integrations](metrics/ci_integrations) - a CLI application that integrates with popular CI tools, such as Jenkins, GitHub Actions, and Buildkite, to collect software project metrics.
```
Would it be a bit more clear and readable?

2021-05-17 10:41 UTC, solid-vovabeloded commented on readme.md
> +[Guardian](guardian) is a tool for detecting and notifying about flaky tests by analyzing JUnit XML files. This tool accepts the unit test reports and compares the actual and previous test results st
```suggestion
[Guardian](guardian) is a tool designed for detecting and notifying about flaky tests by analyzing JUnit XML files. This tool accepts the unit test reports and compares the actual and previous test results stored in a database. If the test is considered flaky, Guardian notifies the team using Slack and creates an issue in Jira.
```
Does it make sense? What do you think?

2021-05-17 10:41 UTC, solid-vovabeloded commented on readme.md
> +4. [Effective Dart](https://dart.dev/guides/language/effective-dart)
```suggestion
4. [Effective Dart :dart:](https://dart.dev/guides/language/effective-dart)
```
What do you think?

2021-05-17 10:41 UTC, solid-vovabeloded commented on readme.md
> +Consider the following [document](docs/15_dependencies_licenses.md) that describes the licenses for all 3-rd party libraries used in monorepo.
```suggestion
Consider the following [document](docs/15_dependencies_licenses.md) that describes the licenses for all 3-rd party libraries used in projects of this repository.
```
What do you think?

2021-05-17 14:34 UTC, solid-vladlaba requested changes
Well done, @solid-daniyilyevtyushkin @solid-yevheniiashchypeleva! I've added a couple of suggestions below - please let me know what you think!

2021-05-17 14:34 UTC, solid-vladlaba commented on readme.md
> +- Flexible request URL matching (using `ExactPathMatcher` or `RegExpPathMatcher`).
To make each item consistent with the pattern: 
```suggestion
The API Mock server provides the following functionality:

- Verifying requests' authentication (by providing `AuthCredentials`);
- Handling requests with `GET`, `DELETE`, `POST`, `PUT` HTTP methods;
- Matching requests' URL (using `ExactPathMatcher` or `RegExpPathMatcher`).
```
Or: 
```suggestion
The API Mock server allows mocking the following real-server functionality:

- Verify requests' authentication (by providing `AuthCredentials`);
- Handle [or Process (?)] requests with `GET`, `DELETE`, `POST`, `PUT` HTTP methods;
- Handle routing by matching requests' URL (using `ExactPathMatcher` or `RegExpPathMatcher`).
```

2021-05-17 14:34 UTC, solid-vladlaba commented on readme.md
> +First, let's consider we have the following API client, and we need to test its `fetchBar` method:
```suggestion
Consider this short example on how to use the API Mock Server.

Let's assume that we have the following API client with the `fetchBar` method we should cover with tests:
```

2021-05-17 14:34 UTC, solid-vladlaba commented on readme.md
> +[Guardian](guardian) is a tool designed for detecting and notifying about flaky tests by analyzing JUnit XML files. This tool accepts the unit test reports and compares the actual and previous test r
```suggestion
[Guardian](guardian) is a tool designed for detecting flaky tests by analyzing JUnit XML reports and notifying the team about the results. This tool accepts the actual reports and compares them to the stored results in a database. If the test is considered flaky, Guardian notifies the team using Slack and/or Jira integrations.
```

2021-05-17 14:34 UTC, solid-vladlaba commented on readme.md
> +- Converting Dart Maps to YAML formatted strings.
```suggestion
- Parsing the YAML documents to core Dart types.
- Converting Dart Maps to YAML formatted strings.
```

2021-05-17 14:34 UTC, solid-vladlaba commented on readme.md
> +Consider the following [document](docs/15_dependencies_licenses.md) that describes the licenses for all 3-rd party libraries used in projects of this repository.
```suggestion
Consider the [Dependencies Licenses](docs/15_dependencies_licenses.md) document that describes the licenses for all 3-rd party libraries used in projects of this repository.
```
What do you think?

2021-05-17 15:21 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-daniyilyevtyushkin @solid-yevheniiashchypeleva!:rocket:

2021-05-17 15:25 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-daniyilyevtyushkin & @solid-yevheniiashchypeleva!

2021-05-17 17:07 UTC, merged