feat: Add security rules and tests for allowed email domains
platform-platform/monorepo pull request #498
Opened 2020-09-02 10:33 UTC by solid-maxim

Fixes #

## Checklist

- [ ] Documented
- [ ] Unit tested

2020-09-02 14:40 UTC, illia-romanenko reviewed
Great job @solid-maxim @vova-beloded! I did a quick run check to see if I have any suggestions - please let me know what you think of the items I added. Look forward to get back to this once you mark it as not Draft. As for the rules - I think we can skip separate flow for 'password' sign-in provider and make sure that all users email domains should match - I think it might simplify it for now and we can get back to the more complex case with 'password' sign-in provider later on.

2020-09-02 14:40 UTC, illia-romanenko commented on metrics/firebase/firestore/rules/firestore.rules
> +      allow create, update: if isLoggedIn(database) && isProjectGroupValid();
```suggestion
      allow read, delete: if isAccessAuthorized(database);
      allow create, update: if isAccessAuthorized(database) && isProjectGroupValid();
```

2020-09-02 14:40 UTC, illia-romanenko commented on metrics/firebase/test/firestore/rules/builds-test.js
> +  it("does not allow to create a build by an authenticated user with an invalid email domain", async () => {
```suggestion
  it("does not allow to create a build by an authenticated user with not allowed email domain", async () => {
```

2020-09-02 14:40 UTC, illia-romanenko commented on metrics/firebase/test/firestore/rules/test_utils/test-data.js
> +exports.invalidUser = { uid: "uid", email: 'test@invalid.com' };
Should we have 2 users? 
1) sign_in_provider - email
2) sign_in_provider - other/Google

2020-09-04 16:22 UTC, illia-romanenko requested changes
Great job @solid-maxim @vova-beloded! I've added a couple of restructuring suggestions to make sure that the same style followed across the test files - please review. Overall test suite looks great and reliable - thanks for your work on this!

2020-09-04 16:22 UTC, illia-romanenko commented on metrics/firebase/test/firestore/rules/project-groups-test.js
> +   */
Let's locate password auth provider tests before Google ones to simplify working with tests - this will match the order to builds-test.js

2020-09-04 16:22 UTC, illia-romanenko commented on metrics/firebase/test/firestore/rules/project-groups-test.js
> +  });
Let's arrange tests in the order it is in the builds-test.js:

PasswordProviderAllowed
Create
Read
Update
Delete

PasswordProviderNowAllowed
CRUD (same as above)

GoogleProviderAllowed
CRUD (same as above)

GoogleProviderNotAllowed
CRUD (same as above)

Unauthenticated
CRUD (same as above)

2020-09-04 16:22 UTC, illia-romanenko commented on metrics/firebase/test/firestore/rules/projects-test.js
> +   * The google auth provider user specific tests
Please rearrange tests in this file as well using the order provided in the project groups comment.

2020-09-08 13:27 UTC, solid-vladlaba requested changes
Well done @solid-maxim @vova-beloded! I've added a couple of suggestions - please let me think what you think!

2020-09-08 13:27 UTC, solid-vladlaba commented on metrics/firebase/test/firestore/rules/builds-test.js
> +  it("does not allow to delete a by an authenticated password user build with not allowed email domain", async () => {
```suggestion
  it("does not allow to delete a built by an authenticated password user build with not allowed email domain", async () => {
```
?

2020-09-08 13:27 UTC, solid-vladlaba commented on metrics/firebase/test/firestore/rules/projects-test.js
> +  it("does not allow to create a project by an authenticated google user with not allowed email domain", async () => {
```suggestion
  it("does not allow creating a project by an authenticated google user with not allowed email domain", async () => {
```
Here and in previous, and next tests.

2020-09-09 19:33 UTC, illia-romanenko commented
As we discussed today - let's test a bit more potential limits imposed by `exists` as @solid-vladlaba suggested.

2020-09-11 16:42 UTC, illia-romanenko commented
@solid-maxim - I have a suggestion: can we use parametrized tests here? 

We want to make the tests more readable and understandable so it feels like it would be a great improvement in terms of the amount of code and ease of the navigation. See an example here: https://stackoverflow.com/questions/17569382/parametrized-tests-with-mocha

I think if we group tests by security rules role and pass different users that should help.

2020-09-14 17:23 UTC, illia-romanenko requested changes
Excellent job @solid-maxim! I've added couple suggestions via chat - let's check after it's finished so we can close it. Thanks!

2020-09-15 09:48 UTC, illia-romanenko approved these changes
LGTM - thanks @solid-maxim @vova-beloded !

2020-09-15 10:14 UTC, vladlaba approved these changes

2020-09-15 10:18 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-maxim @vova-beloded ! 🚀

2020-09-15 10:22 UTC, illia-romanenko commented
@mergifyio refresh

2020-09-15 10:23 UTC, merged