build: Upgrade flutter version
platform-platform/monorepo pull request #538
Opened 2020-09-11 15:39 UTC by solid-yuriiuvarov

Fixes #268

## Checklist

- [ ] Documented
- [ ] Unit tested
- [ ] Component tested

2020-09-15 12:30 UTC, solid-dimakoniaiev commented on metrics/web/lib/base/presentation/graphs/circle_percentage.dart
> -          alignment: Alignment.center,
Maybe we can just use a Center widget for this?

2020-09-15 17:50 UTC, solid-vladlaba requested changes
Tremendous work guys, @solid-yuriiuvarov @solid-dimakoniaiev! 👍 
Like changes related to a new version and lint related changes as well. I have a couple of suggestions below - let me know what you think!

2020-09-15 17:50 UTC, solid-vladlaba commented on metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
> +      "applies the positive icon color form the metrics theme to the network image when the add project group card is enabled",
```suggestion
      "applies the positive icon color form the metrics theme to the add icon when the add project group card is enabled",
```

2020-09-15 17:50 UTC, solid-vladlaba commented on metrics/web/test/project_groups/presentation/widgets/add_project_group_card_test.dart
> +      "applies the inactive icon color form the metrics theme to the network image when the add project group card is disabled",
```suggestion
      "applies the inactive icon color form the metrics theme to the add icon when the add project group card is disabled",
```

2020-09-16 14:29 UTC, solid-dimakoniaiev commented on metrics/web/lib/common/presentation/user_menu_button/theme/user_menu_button_theme_data.dart
> +  const UserMenuButtonThemeData({this.activeColor, this.inactiveColor});
Yes, we're sure)

2020-09-16 17:46 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-dimakoniaiev @solid-yuriiuvarov!:rocket: 
Perfect work! Love changes with TappableArea 🙂

2020-09-16 18:01 UTC, merged