feat: Add password toggle visibility icon.
platform-platform/monorepo pull request #544
Opened 2020-09-14 15:19 UTC by solid-dimakoniaiev

Fixes #533

## Checklist

- [ ] Documented
- [ ] Unit tested

2020-09-15 14:44 UTC, illia-romanenko commented
Designers updated icon - please update the implementation.

2020-09-16 10:49 UTC, solid-vladlaba requested changes
Well done, @solid-dimakoniaiev @solid-yuriiuvarov! I've added a couple of suggestions below - please let me think what do you think!

2020-09-16 10:49 UTC, solid-vladlaba commented on metrics/web/lib/common/presentation/widgets/metrics_text_form_field.dart
> +            decoration: _decoration.copyWith(
I like this! But could you please check that the prefix icon matches the design (for the search field, for example)?

2020-09-16 10:49 UTC, solid-vladlaba commented on metrics/web/test/auth/presentation/widgets/auth_form_test.dart
> +      "applies an eye_on.svg, if the password is obscure",
```suggestion
      "applies the enabled eye icon to the password input field if the password is obscured",
```

2020-09-16 10:49 UTC, solid-vladlaba commented on metrics/web/test/auth/presentation/widgets/auth_form_test.dart
> +      "applies an eye_off.svg, if the password is not obscure",
```suggestion
      "applies the disabled eye icon to the password input field if the password is not obscured",
```

2020-09-16 10:49 UTC, solid-vladlaba commented on metrics/web/test/auth/presentation/widgets/auth_form_test.dart
> +      of: find.byType(MetricsTextFormField),
Should we ensure that the icon set as a suffix icon of the text field? This finder does not ensure that.

2020-09-16 12:27 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-dimakoniaiev @solid-yuriiuvarov !

2020-09-16 12:28 UTC, merged