fix: Icon buttons on hover state should be a bit darker
platform-platform/monorepo pull request #570
Opened 2020-09-17 09:37 UTC by solid-daniyilyevtyushkin

Fixes #559 

## Checklist

- [x] Documented
- [x] Unit tested
- [x] Component tested
- [x] Driver tested

2020-09-17 11:19 UTC, solid-vladlaba requested changes
Well done, @solid-daniyilyevtyushkin! I've added a couple of suggestions below - please let me know what you think!

2020-09-17 11:19 UTC, solid-vladlaba commented on metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
> +                          return IconLabelButton(
Maybe we can introduce the hover parameters to the IconLabelButton and move the TappableArea logic to the IconLabelButton implementation? Also, I suppose we should think about implementing a similar approach as for MetricsButton. E.g., create the MetricsIconLabelButton and introduce the PositiveIconLabelButton, Negative... and so on.

cc @illia-romanenko @vova-beloded

2020-09-17 11:19 UTC, solid-vladlaba commented on metrics/web/lib/common/presentation/metrics_theme/model/light_metrics_theme_data.dart
> +            accentHoverColor: ColorConfig.accentButtonHoverColor,
In addition to the suggestion below, I think we can use the MetricsButtonThemeData for MetricsIconLabelButton. I've noticed that icon buttons have similar styles in the design.

2020-09-18 15:26 UTC, vova-beloded requested changes
Great job, @solid-daniyilyevtyushkin & @solid-vladlaba! I've added a couple of suggestions - please let me know what do you think.

2020-09-18 15:26 UTC, vova-beloded commented on metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
> +                        onPressed: () => _showEditProjectGroupDialog(),
Maybe the previous version was better?  The same for `_showDeleteProjectGroupDialog`.

2020-09-18 15:26 UTC, vova-beloded commented on metrics/web/lib/project_groups/presentation/widgets/project_group_card.dart
> +                                : theme.primaryButtonStyle.color,
Would it be better to extract it to the variable to avoid duplication? The same for `theme.accentButtonStyle`.

2020-09-18 15:26 UTC, vova-beloded commented on metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
> +    this.iconBuilder,
Maybe we can set the default params for these fields to avoid passing them in each test?

2020-09-18 15:26 UTC, vova-beloded commented on metrics/web/test/base/presentation/widgets/icon_label_button_test.dart
> +        await tester.pump();
Maybe we can extract this part of the code to functions to avoid duplication?

2020-09-18 15:26 UTC, vova-beloded commented on metrics/web/test/project_groups/presentation/widgets/project_group_card_test.dart
> +      color: testPrimaryColor,
```suggestion
      color: primaryButtonColor,
```
?

2020-09-21 10:42 UTC, vova-beloded approved these changes
LGTM, thanks @solid-daniyilyevtyushkin!

2020-09-21 10:45 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-daniyilyevtyushkin!:rocket:

2020-09-21 10:53 UTC, merged