feat: doctor command refactor
platform-platform/monorepo pull request #702
Opened 2020-10-14 09:40 UTC by radekdymacz

Fixes #

## Checklist

- [x] Documented

2020-10-14 17:05 UTC, bootstraponline commented on metrics/deploy/lib/doctor/doctor_command.dart
> +  final _fluter = FlutterCommand();
I think this is a typo?

2020-10-14 17:33 UTC, radekdymacz commented on metrics/deploy/lib/doctor/doctor_command.dart
> +  final _fluter = FlutterCommand();
oops will fix that

2020-10-15 08:44 UTC, solid-vovabeloded requested changes
The changes look great, @radekdymacz! I've added a couple of suggestions considering documentation - please take a look.

2020-10-15 08:44 UTC, solid-vovabeloded commented on metrics/deploy/lib/cli/firebase/firebase_command.dart
> +  /// Print cli verison.
Please, start the method documentation with third-person verbs as [effective dart](https://dart.dev/guides/language/effective-dart/documentation#prefer-starting-function-or-method-comments-with-third-person-verbs) advises. The same suggestion for methods in the `FlutterCommand`, `GcloudCommand`, `GitCommand`, and `DoctorCommand`. 
```suggestion
  /// Prints CLI version.
```

2020-10-15 08:44 UTC, solid-vovabeloded commented on metrics/deploy/lib/cli/flutter/flutter_command.dart
> +/// class wrapping up flutter CLI
Please, format the documentation as sentences (see [effective dart](https://dart.dev/guides/language/effective-dart/documentation#do-format-comments-like-sentences) suggestion). The same for all the rest classes.
```suggestion
/// A wrapper class for the Flutter CLI.
```

2020-10-15 08:44 UTC, solid-vovabeloded commented on metrics/deploy/lib/cli/git/git_command.dart
> +  /// Git clone command.
Would it be more clear?
```suggestion
  /// Clones the git repository from the given [repoURL] to the given [srcPath].
```

2020-10-20 15:47 UTC, solid-vovabeloded requested changes
Great job so far, @radekdymacz & @solid-tetianamovlian! I've added a couple of suggestions here - please take a look.

2020-10-20 15:47 UTC, solid-vovabeloded commented on metrics/deploy/lib/cli/firebase/firebase_command.dart
> +  /// Logins to GCloud and Firebase and gets firebase CI token.
```suggestion
  /// Logins to GCloud and Firebase and gets the Firebase CI token.
```

2020-10-20 15:47 UTC, solid-vovabeloded commented on metrics/deploy/lib/cli/gcloud/gcloud_command.dart
> +  /// Logins to GCloud and Firebase and gets firebase CI token.
```suggestion
  /// Logins to GCloud and Firebase and gets a firebase CI token.
```

2020-10-20 15:47 UTC, solid-vovabeloded commented on metrics/deploy/lib/cli/gcloud/gcloud_command.dart
> +  /// Adds project app needed to create firestore database.
```suggestion
  /// Adds project app needed to create a Firestore database.
```

2020-10-20 15:47 UTC, solid-vovabeloded commented on metrics/deploy/lib/cli/gcloud/gcloud_command.dart
> +  /// Adds project or uses existing project.
```suggestion
  /// Adds project or uses an existing one.
```

2020-10-20 15:47 UTC, solid-vovabeloded commented on metrics/deploy/lib/cli/gcloud/gcloud_command.dart
> +  /// Creates firestore database with the given [region] and [projectID].
```suggestion
  /// Creates a Firestore database with the given [region] and [projectID].
```

2020-10-20 15:47 UTC, solid-vovabeloded commented on metrics/deploy/lib/doctor/doctor_command.dart
> +  /// Provides Firebase CLI.
```suggestion
  /// A [FirebaseCommand] needed to get the Firebase CLI version.
```
The same for all fields below.

2020-10-20 15:47 UTC, solid-vovabeloded commented on metrics/deploy/lib/doctor/doctor_command.dart
> +  /// Creates this doctor command instance.
Maybe we can remove this constructor since the class has an empty constructor by default?

2020-10-21 08:46 UTC, solid-vovabeloded approved these changes
LGTM, thanks @radekdymacz & @solid-tetianamovlian! 🚀

2020-10-21 08:54 UTC, merged