test: Buildkite client tests
platform-platform/monorepo pull request #793
Opened 2020-11-10 09:04 UTC by solid-maxim

Fixes #766 

## Checklist

- [ ] Documented
- [ ] Unit tested

2020-11-10 17:26 UTC, solid-vovabeloded requested changes
Great job, @solid-daniyilyevtyushkin & @solid-maxim! I've added a couple of suggestions here - please take a look.

2020-11-10 17:26 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
> +  /// parsed from the given [finishedFrom].
```suggestion
  /// Returns `null` if the `finishedFrom` is `null` or the [DateTime] can't be
  /// parsed from the given `finishedFrom`.
```

2020-11-10 17:26 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/client/buildkite/test_utils/mock/buildkite_mock_server.dart
> +  /// and [finishedFrom].
Should we update the documentation of the `_pipelineBuildsResponse` method to include info about the `finishedFrom` parameter?

2020-11-11 09:59 UTC, solid-vovabeloded requested changes
Almost there, @solid-daniyilyevtyushkin & @solid-maxim! I've added a few suggestions here - hope they make sense.

2020-11-11 09:59 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
> +        final buildsPage = interactionResult.result;
```suggestion
        const buildsPage = BuildkiteBuildsPage(
          page: 1,
          perPage: 1,
        );
```
Does it make sense?

2020-11-11 09:59 UTC, solid-vovabeloded commented on metrics/ci_integrations/test/client/buildkite/buildkite_client_test.dart
> +        );
Maybe we can inline `buildNumber` here?

2020-11-11 12:47 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-maxim  & @solid-daniyilyevtyushkin!

2020-11-11 13:14 UTC, solid-daniyilyevtyushkin commented
@Mergifyio refresh

2020-11-11 13:15 UTC, merged