test: Driver tests improvements
platform-platform/monorepo pull request #840
Opened 2020-11-25 15:39 UTC by solid-daniyilyevtyushkin

Fixes #831

## Checklist

- [x] Documented

2020-11-25 18:41 UTC, solid-vladlaba requested changes
Well done, @solid-daniyilyevtyushkin @solid-maxim! I've added a couple of suggestions below - please let me know what you think!

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/arguments/model/driver_test_arguments.dart
> +  /// [chromedriverVersion] is the version of the chromedriver.
So, as we've touched this file, should we refactor the documentation here to be over each field instead of the constructor? 🙂

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/arguments/parser/driver_test_arguments_parser.dart
> +          'The chromedriver version to use for tests. Uses the latest version if not specified.',
```suggestion
          'The chromedriver version to use for tests. If not specified, the latest version is used.',
```

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/cli/web_driver/chrome_driver.dart
> +  /// Returns a name of the Chromedriver compatible with the current [Platform].
```suggestion
  /// Returns the name of the Chromedriver compatible with the current [Platform].
```

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/cli/web_driver/chrome_driver.dart
> +  String _getPlatformDriverName() {
```suggestion
  String _getDriverArchiveName() {
```

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/cli/web_driver/chrome_driver.dart
> +    final platformDriverName = _getPlatformDriverName();
```suggestion
    final driverArchiveName = _getPlatformDriverName();
```

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/common/config/driver_tests_config.dart
> +  static const String macosDriverName = 'chromedriver_mac64.zip';
```suggestion
  static const String macosDriverArchiveName = 'chromedriver_mac64.zip';
```
Please apply for other platforms as well.

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/common/config/driver_tests_config.dart
> +  /// A Chromedriver name for macOS.
```suggestion
  /// A name of the archive with the Chromedriver for MacOS.
```

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/common/config/driver_tests_config.dart
> +  static const String baseDownloadPath =
```suggestion
  static const String chromedriverUrlBasePath =
```

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/util/chrome_driver_utils.dart
> +    final response = await http.get(latestVersionUrl);
```suggestion
    final response = await http.get('${DriverTestsConfig.chromedriverUrlBasePath}/LATEST_RELEASE');
```
Would it be enough here?

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/util/chrome_driver_utils.dart
> +    return response.body;
Should we throw an error if the status is not successful to indicate that the version fetching is failed and tests cannot be completed properly so CI can react to this?

2020-11-25 18:41 UTC, solid-vladlaba commented on metrics/web/test_driver/common/config/driver_tests_config.dart
> +  /// A base URL download path for the Chromedriver.
```suggestion
  /// A base path for the Chromedriver related URLs.
```

2020-11-26 13:08 UTC, solid-vladlaba submitted a review, later dismissed
Almost there, @solid-daniyilyevtyushkin @solid-maxim! A few more suggestions here - please take a look!

Also, I'd like to suggest @solid-vovabeloded review these changes as well as he has more experience with driver tests and may notice something I missed.

2020-11-26 13:08 UTC, solid-vladlaba commented on metrics/web/test_driver/arguments/model/driver_test_arguments.dart
> +  /// The directory to run all the commands.
```suggestion
  /// A working directory to run all the commands.
```

2020-11-26 13:08 UTC, solid-vladlaba commented on metrics/web/test_driver/arguments/model/driver_test_arguments.dart
> +  /// The directory to store the logs from commands.
```suggestion
  /// A directory to store the logs from commands.
```
Please apply the same to the fields below.

2020-11-26 13:08 UTC, solid-vladlaba commented on metrics/web/test_driver/arguments/model/driver_test_arguments.dart
> +  /// The name of the browser, used to run the tests.
```suggestion
  /// A name of the browser that is used to run the tests.
```

2020-11-26 13:08 UTC, solid-vladlaba commented on metrics/web/test_driver/arguments/model/driver_test_arguments.dart
> +  /// Specifies whether run all commands with the `--verbose` flag or not.
```suggestion
  /// Indicates whether to run all commands with the `--verbose` flag or not.
```

2020-11-26 13:08 UTC, solid-vladlaba commented on metrics/web/test_driver/arguments/model/driver_test_arguments.dart
> +  /// Disables any prints to the console.
```suggestion
  /// Indicates whether to disable any prints to the console from commands or not.
```

2020-11-26 13:08 UTC, solid-vladlaba commented on metrics/web/test_driver/arguments/model/driver_test_arguments.dart
> +  /// Specifies whether to print the usage information or not.
```suggestion
  /// Indicates whether to print the usage information or not.
```

2020-11-26 15:05 UTC, solid-vovabeloded requested changes
Great job, @solid-maxim & @solid-daniyilyevtyushkin! I've added a couple of suggestions here - please take a look.

2020-11-27 13:07 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-daniyilyevtyushkin & @solid-maxim!

2020-11-27 13:47 UTC, illia-romanenko commented
@mergifyio refresh

2020-11-27 13:47 UTC, merged