fix: Update light and dark tooltip colors
platform-platform/monorepo pull request #899
Opened 2020-12-15 11:44 UTC by solid-yevheniiashchypeleva

Fixes #897

## Checklist

2020-12-15 17:14 UTC, solid-vladlaba requested changes
Well done, @solid-daniyilyevtyushkin @solid-yevheniiashchypeleva! I've added one small suggestion below - please let me know what you think!

2020-12-15 17:14 UTC, solid-vladlaba commented on metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
> +                valueColor: ColorConfig.shimmerColor,
Seems like this color doesn't match the design 
![image](https://user-images.githubusercontent.com/70939496/102248167-8e532000-3f09-11eb-8a65-75d3f2fe87e7.png)

2020-12-16 07:51 UTC, solid-daniyilyevtyushkin commented on metrics/web/lib/common/presentation/metrics_theme/model/dark_metrics_theme_data.dart
> +                valueColor: ColorConfig.shimmerColor,
This color is defined in `icons/unknown_status.svg`, but we'll update it, though.

![Снимок экрана 2020-12-16 в 09 50 30](https://user-images.githubusercontent.com/69351065/102319837-22fa6400-3f84-11eb-87fe-d42cb586c24f.png)

2020-12-16 10:08 UTC, solid-vladlaba approved these changes
LGTM, thanks @solid-daniyilyevtyushkin @solid-yevheniiashchypeleva!:rocket:

2020-12-16 10:09 UTC, merged