Change sentry design
platform-platform/monorepo pull request #943
Opened 2020-12-28 17:15 UTC by solid-vladlaba

Fixes #940

## Checklist

- [x] Documented

2020-12-28 20:06 UTC, illia-romanenko requested changes
Great job @solid-vladlaba @solid-dimakoniaiev! Excited to see all the design changes and they look awesome. I've added a couple of suggestions - please let me know what you think. 
Overall this is a very solid document that I enjoyed reading, diagrams very helpful!

2020-12-28 20:12 UTC, illia-romanenko commented on metrics/web/docs/features/metrics_logger/diagrams/metrics_logger_class_diagram.puml
> +    + static logError(Object error, [Object stackTrace]) : Future<void>
Can we specify stackTrace type to be StackTrace? Can you ping me so we can discuss this - I feel that I miss something here.

2020-12-29 13:48 UTC, illia-romanenko approved these changes
Phenomenal work @solid-vladlaba & @solid-dimakoniaiev - this document is a great exploration of the Logger approach, Sentry, and ready to be extended with any other logging library.

2020-12-29 17:51 UTC, solid-vovabeloded approved these changes
LGTM, thanks @solid-vladlaba & @solid-dimakoniaiev! The document looks awesome and clearly explains the implementation of the `MetricsLogger`!

2020-12-29 18:14 UTC, merged